#spring.application.name=customer
server:
  port: ${PORT:8080}

spring:
  application:
    name: Finance-Tracking

  datasource:
    url: jdbc:mysql://mysql-db:3306/tracker
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jwt:
  secret: "mySuperSecureSecretKeyForJwtTokenGeneration123!"
  expiration-ms: 86400000 # 1 day in milliseconds