#spring.application.name=customer
server:
  port: ${PORT:8080}

spring:
  application:
    name: Finance-Tracking
  profiles:
    active: local

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
  ai:
    ollama:
      url: http://localhost:11434
      model: qwen2.5-coder:7b
jwt:
  secret: "mySuperSecureSecretKeyForJwtTokenGeneration123!"
  expiration-ms: 86400000 # 1 day in milliseconds
logging:
  level:
    org.springframework.boot: INFO
