#spring.application.name=customer
server:
  port: ${PORT:8080}

spring:
  application:
    name: Finance-Tracking
  profiles:
    active: local

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
  ai:
    ollama:
      url: http://localhost:11434
      model-chat: qwen2.5-coder:7b
      model-embedding: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1024
        index-type: hnsw
        distance-type: cosine_distance
jwt:
  secret: "mySuperSecureSecretKeyForJwtTokenGeneration123!"
  expiration-ms: 86400000 # 1 day in milliseconds
logging:
  level:
    org.springframework.boot: INFO

vector:
  datasource:
    url: jdbc:postgresql://localhost:5433/vectordb
    username: postgres
    password: postgres

  store:
    initialize-schema: true
    dimensions: 1024